splash = true
ipc = true


wallpaper {
    monitor = DP-1
    path = /home/akishu/Pictures/Monitor-Middle.jpg
    fit_mode = cover
}


wallpaper {
    monitor = DP-2
    path = /home/akishu/Pictures/Monitor-Right.png
    fit_mode = cover
}


wallpaper {
    monitor = HDMI-A-1
    path = /home/akishu/Pictures/Monitor-Left.png
    fit_mode = cover
}