preload = /home/akishu/Pictures/Monitor-Middle.png
preload = /home/akishu/Pictures/Monitor-Left.jpg
preload = /home/akishu/Pictures/Monitor-Right.png
wallpaper = DP-1, /home/akishu/Pictures/Monitor-Middle.png
wallpaper = HDMI-A-2, /home/akishu/Pictures/Monitor-Left.jpg
wallpaper = HDMI-A-1, /home/akishu/Pictures/Monitor-Right.png