#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3
    layout = dwindle
    col.active_border = rgba(00ffd2cc)
    col.inactive_border = rgba(004687cc)
    resize_on_border = true
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 5
    active_opacity = 0.9
    inactive_opacity = 0.7
    fullscreen_opacity = 1.0
    blur {
        enabled = true
        size = 10
        passes = 2
        new_optimizations = true
    }
    shadow {
        enabled = false
    }
}


# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# default animations
# animations {
#     enabled = true
#
#     bezier = test, 0.5, 0.25, 0.5, 0.75
#
#     animation = windows,     1, 2, test
#     animation = windowsIn,   1, 2, test, popin 95%
#     animation = windowsOut,  1, 2, test, popin 95%
#     animation = windowsMove, 1, 2, test, popin 95%
#     animation = border,      1, 2, test
#     animation = borderangle, 1, 2, test
#     animation = fade,        1, 2, test
#     animation = workspaces,  1, 2, test
# }

# dwindle touchpad
dwindle {
    pseudotile = true
    preserve_split = true
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
#    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}