###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar #dolphin
$menu = wofi --show drun
$browser-fire = firefox

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

# Waybar
exec-once = waybar

# Background pics
exec-once = hyprpaper

# Sync-Module for Obsidian
exec-once = syncthing --no-browser

# Verification stuff
exec-once = systemctl --user start hyprpolkitagent

# Stream-Deck program
exec-once = opendeck --hide

# Clipboard-Manager
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data